### ISSUE TITLE
How to setup pycsdr

### ISSUE THREAD

**Issue by frspin** [jketterl/pycsdr#1]
How to setup pysdr?
Using setup.py give an error:

`sudo python3 setup.py build
/usr/lib/python3/dist-packages/setuptools/dist.py:473: UserWarning: Normalizing '0.18.0-dev' to '0.18.0.dev0'
  warnings.warn(
running build
running build_py
package init file 'pycsdr/__init__.py' not found (or not a regular file)
running build_ext
building 'pycsdr.modules' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Isrc -I/usr/include/python3.8 -c src/pycsdr.cpp -o build/temp.linux-x86_64-3.8/src/pycsdr.o
In file included from src/buffer.h:6,
                 from src/pycsdr.cpp:2:
src/writer.hpp:5:10: fatal error: csdr/writer.hpp: File o directory non esistente
    5 | #include <csdr/writer.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
`

Same error using default branch of csdr and csdr++ branch
I am using Ubuntu 20.04 64 bit 

Regards
Franco Spinelli
IW2DHW

**Comment by jketterl** [comment]
I don't know what brought you here, but this code is not even finished yet, so I'm not surprised that you're getting errors.

This library relies on the refactoring of csdr that's currently present in the csdr++ branch of https://github.com/jketterl/csdr

If it doesn't compile, you will need to check for yourself what's wrong. It looks like your compiler is missing a header file, so the first step would be to check if that was installed correctly.

**Comment by frspin** [comment]
I know that this library is non finished and also based on csdr++
I have also cloned csdr++ from GIT repo but installing this version don't install required include files, only libcsdr.h and libcsdr.so.0.18.0 in /usr/local/lib

Regards

Franco Spinelli
IW2DHW

**Comment by jketterl** [comment]
please distinguish between csdr (repository) and csdr++ (branch). when you clone csdr, you are normally on the develop branch. that does not contain the necessary code to build this.

**Comment by frspin** [comment]
I have downloaded csdr++ branch in a new directory.
I will control if this is correct or if I need some other GIT command for this

Regards
Franco Spinelli
IW2DHW

**Comment by frspin** [comment]
My fault. Change to csdr++ branch was wrong
Redone clone, correctly done git checkout cdsr++ and now all is working. Problem solved.

Tanks

Franco Spinelli
IW2DHW
