### ISSUE TITLE
Arch makepkg fails looking for baudot.hpp

### ISSUE THREAD

**Issue by ahmogit** [jketterl/pycsdr#7]
I'm new to openwebrx, so the following is most likely due to my ignorance regarding dependency resolution. Nevertheless was unable to get past this, so seeking some assistance.

Platform Arch linux, commodity laptop:

  1. Starting with Arch AUR package openwebrx: Its makepkg bails on dependency python-csdr.
  2. Download python-csdr-git, attempt "makepkg".
  3. makepkg on python-csdr-git fails, seeking #include of <csdr/baudot.hpp> (which is not installed on my system).
  
Is there a missing dependency in the PKGBUILD? Or am I making some silly mistake in my assuption as to how to go about satisfying the python-csdr dependency?

Stdout and stderr from Step 3 above attached.

TIA.

[makepkg_stdout.txt](https://github.com/user-attachments/files/17445653/makepkg_stdout.txt)
[makepkg_stderr.txt](https://github.com/user-attachments/files/17445656/makepkg_stderr.txt)

**Comment by jketterl** [comment]
I'm sorry, but you'll have to report this to the people who maintain the AUR packages descriptions. The problem here is that you have a mix of different versions (note the `-git` suffix on some of the packages), and to make things worse, I believe they also use versions that have been forked off. It is beyond me to fix this.

**Comment by ahmogit** [comment]
Hmm, yes, I see what you mean. The Arch AUR PKGBUILDs seem to be in need of some work.

Among other problems, the PKGBUILD for pycsdr is evidently in error by depend()ing on "csdr", rather than your version (csdr-jketterl-git). Another AUR user had actually pointed this out in the AUR comments but I missed it, just saw it now. Anyway, with your csdr pkg installed, python-csdr-git now builds to completion.

However... there are now several further dependency-confusion issues as well, but I can take it from here to get those resolved

In any case, tip o' the hat for your time in responding so quickly. Hopefully I should be able to proceed from here.
